from __future__ import annotations

import flet as ft

PAGE_SWITCH_DURATION = 260
PAGE_SWITCH_REVERSE_DURATION = 180
PAGE_SWITCH_IN_CURVE = ft.AnimationCurve.EASE_OUT_CUBIC
PAGE_SWITCH_OUT_CURVE = ft.AnimationCurve.EASE_IN_CUBIC

CARD_REVEAL_OPACITY_DURATION = 260
CARD_REVEAL_OFFSET_DURATION = 320
CARD_REVEAL_CURVE = ft.AnimationCurve.EASE_OUT_CUBIC
CARD_REVEAL_STAGGER_MS = 45

BUTTON_HOVER_DURATION = 160
BUTTON_HOVER_CURVE = ft.AnimationCurve.EASE_OUT

NAV_ITEM_DURATION = 180
NAV_ITEM_CURVE = ft.AnimationCurve.EASE_OUT

NOTIFICATION_FADE_DURATION = 300
NOTIFICATION_FADE_CURVE = ft.AnimationCurve.EASE_OUT_CUBIC

GENERAL_DURATION = 180
GENERAL_CURVE = ft.AnimationCurve.EASE_OUT

LOADING_SPINNER_DURATION = 800
LOADING_SPINNER_CURVE = ft.AnimationCurve.EASE_IN_OUT

LOADING_OVERLAY_FADE_DURATION = 250
LOADING_OVERLAY_FADE_CURVE = ft.AnimationCurve.EASE_OUT

DIALOG_OPEN_DURATION = 200
DIALOG_OPEN_CURVE = ft.AnimationCurve.EASE_OUT_CUBIC

STATUS_PILL_DURATION = 200
STATUS_PILL_CURVE = ft.AnimationCurve.EASE_OUT

PAGE_SWITCH = ft.Animation(PAGE_SWITCH_DURATION, PAGE_SWITCH_IN_CURVE)
PAGE_SWITCH_REVERSE = ft.Animation(PAGE_SWITCH_REVERSE_DURATION, PAGE_SWITCH_OUT_CURVE)

CARD_REVEAL_OPACITY = ft.Animation(CARD_REVEAL_OPACITY_DURATION, CARD_REVEAL_CURVE)
CARD_REVEAL_OFFSET = ft.Animation(CARD_REVEAL_OFFSET_DURATION, CARD_REVEAL_CURVE)

BUTTON_HOVER = ft.Animation(BUTTON_HOVER_DURATION, BUTTON_HOVER_CURVE)
NAV_ITEM = ft.Animation(NAV_ITEM_DURATION, NAV_ITEM_CURVE)
NOTIFICATION_FADE = ft.Animation(NOTIFICATION_FADE_DURATION, NOTIFICATION_FADE_CURVE)
GENERAL = ft.Animation(GENERAL_DURATION, GENERAL_CURVE)
LOADING_OVERLAY_FADE = ft.Animation(LOADING_OVERLAY_FADE_DURATION, LOADING_OVERLAY_FADE_CURVE)
DIALOG_OPEN = ft.Animation(DIALOG_OPEN_DURATION, DIALOG_OPEN_CURVE)
STATUS_PILL = ft.Animation(STATUS_PILL_DURATION, STATUS_PILL_CURVE)
