SURFACE_BG = "#0D1117"
SURFACE_SIDEBAR = "#111827"
SURFACE_LOW = "#161B22"
SURFACE = "#1F2630"
SURFACE_HIGH = "#27313F"
SURFACE_HIGHEST = "#303B4C"

OUTLINE = "#3D4756"
OUTLINE_SOFT = "#2B3442"

TEXT_PRIMARY = "#EEF3FA"
TEXT_SECONDARY = "#B5C0CC"
TEXT_MUTED = "#7E8A99"

KLEIN_BLUE = "#2F65FF"
KLEIN_BLUE_SOFT = "#86A8FF"
KLEIN_BLUE_DARK = "#183A91"

CORAL = "#FF8A7A"
CORAL_DARK = "#7D3632"

MINT = "#8BE0B0"
MINT_DARK = "#255B40"

WARNING = "#FFD38A"

SHADOW = "#000000"
TRANSPARENT = "transparent"

LOADING_SPINNER = KLEIN_BLUE_SOFT
LOADING_SPINNER_TRACK = OUTLINE_SOFT
LOADING_DOT = KLEIN_BLUE
LOADING_DOT_INACTIVE = SURFACE_HIGHEST
SKELETON_BASE = SURFACE_HIGH
SKELETON_SHINE = SURFACE_HIGHEST
OVERLAY_DIM = "#B3000000"
OVERLAY_BG = SURFACE_BG

STATUS_RUNNING_BG = "#1D3F32"
STATUS_COMPLETED_BG = "#1D3F32"
STATUS_FAILED_BG = "#4A282A"
STATUS_STOPPED_BG = "#4A3D24"
STATUS_IDLE_BG = "#22345F"

GRADIENT_BLUE = (KLEIN_BLUE, KLEIN_BLUE_DARK)
GRADIENT_BLUE_SOFT = (KLEIN_BLUE_SOFT, KLEIN_BLUE)
GRADIENT_SURFACE = (SURFACE_HIGH, SURFACE)
GRADIENT_GLOW = (KLEIN_BLUE, "#7B2FFF")
GRADIENT_DARK = (SURFACE_LOW, SURFACE_BG)
GRADIENT_MINT = (MINT, MINT_DARK)
GRADIENT_CORAL = (CORAL, CORAL_DARK)
GRADIENT_WARNING = (WARNING, "#7A5A1A")
